- name: Install xcode-install gem
  gem:
    name: xcode-install
    include_doc: false
    user_install: false
    state: latest
    executable: /usr/bin/gem
  become: true

- name: Apply patch to use codesign 
  patch:
    src: xcode_install_use_codesign_to_verify.diff
    basedir: /Library/Ruby/Gems/2.3.0/gems/xcode-install-2.5.0
    strip: 0
  become: true

- name: Install Xcode {{ xcode_version }}
  xcode:
    version: "{{ xcode_version }}"
  environment:
    GEM_HOME: "{{ system_gem_dir }}"
    GEM_PATH: "{{ system_gem_dir }}"
    XCODE_INSTALL_USER: "{{ xcode_install_user }}"
    XCODE_INSTALL_PASSWORD: "{{ xcode_install_password }}"
