- name: Check if Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: homebrew_installed

- name: Update Homebrew
  command: /usr/local/bin/brew update

- name: Gather installed versions of packages
  command: /usr/local/bin/brew ls --versions
  register: brew_versions

- name: Write installed packages to file
  copy:
    content: "{{ brew_versions.stdout }}"
    dest: /tmp/brew_packages
