- name: Check if Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: homebrew_installed

- name: Update Homebrew
  command: /usr/local/bin/brew update

- name: Upgrade readline
  command: /usr/local/bin/brew reinstall readline

- name: Upgrade gdbm
 command: /usr/local/bin/brew reinstall gdbm  

- name: Gather installed versions of packages
  command: /usr/local/bin/brew ls --versions
  register: brew_versions

- name: "Symlinking readline lib"
  file:
    state: link
    force: yes
    src: /usr/local/opt/readline/lib/libreadline.dylib
    dest: /usr/local/opt/readline/lib/libreadline.7.dylib

- name: "Symlinking gdbm lib"
  file:
    state: link
    force: yes
    src: /usr/local/opt/gdbm/lib/libgdbm.dylib
    dest: /usr/local/opt/gdbm/lib/libgdbm.5.dylib

# - name: Install Ruby 2.6.3
  # command: /Users/travis/.rvm/bin/rvm install 2.6.3 --binary --fuzzy

#- name: Write installed packages to file
#  copy:
#    content: "{{ brew_versions.stdout }}"
#    dest: /tmp/brew_packages
