- name: Install GnuPG
  homebrew:
    name: gpg

- name: Check if RVM is already installed
  stat:
    path: "{{ rvm_binary }}"
  register: rvm_installed

- name: Copy RVM GPG key
  copy:
    src: rvm-gpg.key
    dest: /tmp/rvm-gpg.key
  when: rvm_installed.stat.exists == false

- name: Import RVM GPG key
  command: /usr/local/bin/gpg --import /tmp/rvm-gpg.key
  when: rvm_installed.stat.exists == false

- name: Import mpapis GPG key
  shell: curl -sSL https://rvm.io/mpapis.asc | /usr/local/bin/gpg --import -
  shell: curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
  when: rvm_installed.stat.exists == false

- name: Trust keys
  shell: echo 409B6B1796C275462A1703113804BB82D39DC0E3:6: | gpg --import-ownertrust # mpapis@gmail.com 
  shell: echo 7D2BAF1CF37B13E2069D6956105BD0E739499BDB:6: | gpg --import-ownertrust # piotr.kuczynski@gmail.com


- name: Install RVM
  shell: curl -sSL https://get.rvm.io | bash -s {{ rvm_version }} --ignore-dotfiles
  when: rvm_installed.stat.exists == false

- name: Clean up RVM
  shell: "{{ rvm_binary }} cleanup all"

- name: Copy RVM config file
  copy:
    src: rvmrc
    dest: /Users/travis/.rvmrc
    mode: 0644
    owner: travis

- name: Copy RVM binary server configuration
  copy:
    src: rvm_user_db
    dest: /Users/travis/.rvm/user/db
    mode: 0644
    owner: travis
