---
- hosts: builders
  remote_user: travis
  roles:
  - role: config
    tags: [config]
  - role: ssh
    tags: [ssh]
  - role: homebrew
    tags: [homebrew]
  - role: travis
    tags: [travis]
  - role: cleanup
    tags: [cleanup]
