---
- import_playbook: site.yml
  vars:
    xcode_version: '11.3.1'
    nvm_version: v0.35.2
    node_versions:
    - 13.6.0
    - 12.14.1
    - 10.18.1
    - 8.17.0
    rubies: [2.7.0]
    default_ruby: 2.7.0
