---
- import_playbook: site.yml
  vars:
    xcode_version: '11.4'
    nvm_version: v0.35.3
    node_versions:
    - 13.11.0
    - 12.16.1
    - 10.19.0
    - 8.17.0
    rubies: [2.6.5]
    default_ruby: 2.6.5
